### PR TITLE
Changes to README

### PR DESCRIPTION
**Pull request by prasanna08**
A new PR to check whether Travis is working as expected or not.

### CODE REVIEW

**Comment by prasanna08** [comment]
@seanlip, even here it shows two checks. Moreover, the checks aren't starting according to Travis [status](https://travis-ci.com/github/oppia/oppia-ml/pull_requests) page.

**Comment by seanlip** [comment]
OK, I'm afraid I have no idea. Can you check again with Travis support, please?

**Comment by prasanna08** [comment]
Sure.

**Comment by seanlip** [comment]
In case you need it, here's what I see in the Settings for this repo:

Screenshot from 2020-06-25 01-47-45

**Comment by prasanna08** [comment]
@seanlip, I don't think this is working. The issue has been [reported earlier](https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154), although I am not sure if the same error is causing it. Can you look at it? The old check shows as `required` but new check isn't `required`, I think it has something to do with repo settings.

**Comment by seanlip** [comment]
Closing (I assume you don't really care about merging this PR?) because the underlying issue with Travis has been fixed.

**Pull request closed without merging**
