### PR TITLE
Add travis integration

### PR DESCRIPTION
**Pull request by prasanna08**
This PR adds travis integration in oppia-ml. Also fixes some residual errors in `pre_commit_linter.py`.

### CODE REVIEW

**Comment by prasanna08** [comment]
Hi @seanlip I added travis checks. These won't work until #10 is merged.

**Comment by prasanna08** [comment]
I combined this and #10 in my  repo, and created PR [#3](https://github.com/prasanna08/oppia-ml/pull/3) to test whether travis is working or not.

**Review by seanlip — APPROVED** [review]
LGTM

**Comment by seanlip** [comment]
Looks good! Please merge when you see fit -- I'm not sure whether this should go in before or after #10. Happy to set up the checks on GitHub when it's in.

**Comment by prasanna08** [comment]
Probably after #10. It is meaning less to merge this before that.

**Comment by prasanna08** [comment]
@seanlip you can start oppia-ml in travis dashboard now.

**Comment by seanlip** [comment]
done!

**Pull request merged**
